-- Add demo t-shirt products with patterns
INSERT INTO products (
  id,
  type,
  name,
  description,
  price,
  image_url,
  colors,
  designs,
  stock,
  brand,
  created_at,
  updated_at
) VALUES
(
  gen_random_uuid(),
  'tshirt',
  'Geometric Grid Tee',
  'Modern geometric pattern t-shirt with customizable colors. Perfect for pairing with your favorite sneakers.',
  29.99,
  '/geometric-grid-pattern-grayscale.jpg',
  ARRAY['Black', 'White', 'Red', 'Blue', 'Green', 'Yellow', 'Purple', 'Orange'],
  '[{"name": "Geometric Grid", "thumbnail_url": "/geometric-grid-pattern-grayscale.jpg"}]'::jsonb,
  50,
  'WearMatch',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'tshirt',
  'Hexagon Mesh Tee',
  'Stylish hexagon mesh pattern that adapts to any color palette. A versatile addition to your wardrobe.',
  32.99,
  '/hexagon-mesh-pattern-grayscale.jpg',
  ARRAY['Black', 'White', 'Navy', 'Gray', 'Teal', 'Burgundy'],
  '[{"name": "Hexagon Mesh", "thumbnail_url": "/hexagon-mesh-pattern-grayscale.jpg"}]'::jsonb,
  45,
  'WearMatch',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'tshirt',
  'Triangle Wave Tee',
  'Bold triangle wave design for the fashion-forward. Customize with your preferred color scheme.',
  31.99,
  '/triangle-wave-pattern-grayscale.jpg',
  ARRAY['Black', 'White', 'Red', 'Blue', 'Purple', 'Orange'],
  '[{"name": "Triangle Wave", "thumbnail_url": "/triangle-wave-pattern-grayscale.jpg"}]'::jsonb,
  40,
  'WearMatch',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'tshirt',
  'Flowing Lines Tee',
  'Abstract flowing lines create a dynamic look. Perfect for expressing your unique style.',
  30.99,
  '/flowing-lines-abstract-pattern-grayscale.jpg',
  ARRAY['Black', 'White', 'Blue', 'Teal', 'Purple', 'Gray'],
  '[{"name": "Flowing Lines", "thumbnail_url": "/flowing-lines-abstract-pattern-grayscale.jpg"}]'::jsonb,
  55,
  'WearMatch',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'tshirt',
  'Organic Shapes Tee',
  'Nature-inspired organic shapes in a modern design. Versatile and comfortable.',
  29.99,
  '/organic-shapes-abstract-pattern-grayscale.jpg',
  ARRAY['Black', 'White', 'Green', 'Brown', 'Gray', 'Teal'],
  '[{"name": "Organic Shapes", "thumbnail_url": "/organic-shapes-abstract-pattern-grayscale.jpg"}]'::jsonb,
  48,
  'WearMatch',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'tshirt',
  'Dotted Grid Minimal Tee',
  'Minimalist dotted grid pattern for a clean, sophisticated look.',
  27.99,
  '/dotted-grid-minimal-pattern-grayscale.jpg',
  ARRAY['Black', 'White', 'Gray', 'Navy', 'Burgundy'],
  '[{"name": "Dotted Grid", "thumbnail_url": "/dotted-grid-minimal-pattern-grayscale.jpg"}]'::jsonb,
  60,
  'WearMatch',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'tshirt',
  'Diagonal Stripe Tee',
  'Classic diagonal stripes with a modern twist. Timeless and stylish.',
  28.99,
  '/diagonal-stripe-lines-minimal-pattern-grayscale.jpg',
  ARRAY['Black', 'White', 'Red', 'Blue', 'Navy', 'Gray'],
  '[{"name": "Diagonal Stripes", "thumbnail_url": "/diagonal-stripe-lines-minimal-pattern-grayscale.jpg"}]'::jsonb,
  52,
  'WearMatch',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'tshirt',
  'City Grid Urban Tee',
  'Urban-inspired city grid pattern for the street style enthusiast.',
  33.99,
  '/city-grid-urban-pattern-grayscale.jpg',
  ARRAY['Black', 'White', 'Gray', 'Red', 'Blue', 'Yellow'],
  '[{"name": "City Grid", "thumbnail_url": "/city-grid-urban-pattern-grayscale.jpg"}]'::jsonb,
  42,
  'WearMatch',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'tshirt',
  'Street Art Tee',
  'Bold street art inspired design. Make a statement with your style.',
  34.99,
  '/street-art-urban-pattern-grayscale.jpg',
  ARRAY['Black', 'White', 'Red', 'Orange', 'Purple', 'Blue'],
  '[{"name": "Street Art", "thumbnail_url": "/street-art-urban-pattern-grayscale.jpg"}]'::jsonb,
  38,
  'WearMatch',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'tshirt',
  'Leaf Nature Tee',
  'Nature-inspired leaf pattern for an organic, earthy vibe.',
  30.99,
  '/leaf-nature-pattern-grayscale.jpg',
  ARRAY['Black', 'White', 'Green', 'Brown', 'Teal', 'Gray'],
  '[{"name": "Leaf Pattern", "thumbnail_url": "/leaf-nature-pattern-grayscale.jpg"}]'::jsonb,
  46,
  'WearMatch',
  NOW(),
  NOW()
);
